FROM java:8
COPY ./target/zatech-gaia-amethyst-server.jar /root/startup/
WORKDIR /root/startup/
EXPOSE 8080
EXPOSE 6000
ENTRYPOINT exec java ${JVM_OPTS:- -Xdebug -Xms124m -Xmx124m} -Dspring.active.profile=local -jar /root/startup/zatech-gaia-amethyst-server.jar