pipeline {
    agent any
    stages {
        stage('拉代码') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: ' */${branch}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: 'github', url: 'https://github.com/kingslun/kinglsun.git']]])
            }
        }
        stage('打包代码') {
            steps {
                echo '======================开始构建应用======================'
                sh 'mvn -DskipTests clean package'
            }
        }
        stage('测试代码') {
            steps {
                echo '======================开始执行单侧======================'
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('发布代码') {
            steps {
                echo '======================开始发布应用======================'
                sh 'cd ./target'
                sh 'java -jar kings-docker.jar'
            }
        }
    }
}