logging:
  level.com.kings.framework.docker: debug
spring:
  application:
    name: kings-docker
octopus:
  amethyst:
    client:
      task:
        enable: true
        servers: 192.168.243.125:6000